#!/bin/bash
#Author
#Date
#Desc
#
a=`hostname`
echo my server name name is $a
echo
echo what is your name?
read b
echo
echo what is your profession?
read c
echo
echo what is your favour show
read d
echo
echo Hello $b!
echo
echo your profession $c is awesome
echo $d is a good show
echo
